name: Merge on develop
on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ftripio/catalog-service-dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          cache: true
          cache_registry: ftripio/catalog-service-cache
